import { ProductParams } from "@/shared.types";

// This file provides static product data as a fallback
// In production, all data comes from Supabase

export const sampleProducts: ProductParams[] = [
  {
    id: "1",
    author_id: "",
    name: "Apple Earphones",
    description: "Noise-cancellation, 40-hour battery life, premium sound quality",
    price: 299.99,
    offer_price: 269.99,
    discount: 10,
    quantity: 50,
    brand: "Apple",
    status: "active",
    location: "USA",
    product_shipping_fee: 0,
    product_comment: "",
    sizes: ["S", "M", "L"],
    colors: ["White", "Black"],
    styles: [],
    image_url_array: [
      "/assets/apple_earphone_image.png",
    ],
    videos_url_array: [],
    category: { id: "1", name: "Headphones" },
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    average_rating: 4.5,
    review_count: 128,
  },
  {
    id: "2",
    author_id: "",
    name: "Bose QuietComfort 45",
    description: "Noise Cancellation, 24-hour battery, comfortable fit",
    price: 329.99,
    offer_price: 329.99,
    discount: 0,
    quantity: 35,
    brand: "Bose",
    status: "active",
    location: "USA",
    product_shipping_fee: 0,
    product_comment: "",
    sizes: [],
    colors: ["White", "Black", "Grey"],
    styles: [],
    image_url_array: [
      "/assets/bose_headphone_image.png",
    ],
    videos_url_array: [],
    category: { id: "1", name: "Headphones" },
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    average_rating: 4.7,
    review_count: 89,
  },
  {
    id: "3",
    author_id: "",
    name: "Samsung Galaxy S23",
    description: "AMOLED Display, 50MP Camera, 5G Enabled",
    price: 799.99,
    offer_price: 699.99,
    discount: 12,
    quantity: 20,
    brand: "Samsung",
    status: "active",
    location: "Korea",
    product_shipping_fee: 5.99,
    product_comment: "",
    sizes: ["128GB", "256GB", "512GB"],
    colors: ["Phantom Black", "Green", "Lavender"],
    styles: [],
    image_url_array: [
      "/assets/samsung_s23phone_image.png",
    ],
    videos_url_array: [],
    category: { id: "2", name: "Phones" },
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    average_rating: 4.6,
    review_count: 256,
  },
  {
    id: "4",
    author_id: "",
    name: "Garmin Venu 2",
    description: "GPS Smartwatch, AMOLED Display, 11-day battery",
    price: 349.99,
    offer_price: 349.99,
    discount: 0,
    quantity: 45,
    brand: "Garmin",
    status: "active",
    location: "USA",
    product_shipping_fee: 0,
    product_comment: "",
    sizes: ["40mm", "45mm"],
    colors: ["Black", "Gold", "Grey"],
    styles: [],
    image_url_array: [
      "/assets/venu_watch_image.png",
    ],
    videos_url_array: [],
    category: { id: "5", name: "Watches" },
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    average_rating: 4.4,
    review_count: 67,
  },
  {
    id: "5",
    author_id: "",
    name: "PlayStation 5",
    description: "Ultra-HD Gaming, 825GB SSD, Ray Tracing Graphics",
    price: 499.99,
    offer_price: 499.99,
    discount: 0,
    quantity: 15,
    brand: "Sony",
    status: "active",
    location: "Japan",
    product_shipping_fee: 9.99,
    product_comment: "",
    sizes: ["Standard", "Digital Edition"],
    colors: ["White"],
    styles: [],
    image_url_array: [
      "/assets/playstation_image.png",
    ],
    videos_url_array: [],
    category: { id: "6", name: "Gaming" },
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    average_rating: 4.9,
    review_count: 512,
  },
  {
    id: "6",
    author_id: "",
    name: "Canon EOS R5",
    description: "45MP Sensor, 8K Video Recording, In-Body Stabilization",
    price: 3899.99,
    offer_price: 3499.99,
    discount: 10,
    quantity: 8,
    brand: "Canon",
    status: "active",
    location: "Japan",
    product_shipping_fee: 0,
    product_comment: "",
    sizes: [],
    colors: ["Black"],
    styles: [],
    image_url_array: [
      "/assets/cannon_camera_image.png",
    ],
    videos_url_array: [],
    category: { id: "4", name: "Cameras" },
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    average_rating: 4.8,
    review_count: 34,
  },
  {
    id: "7",
    author_id: "",
    name: "MacBook Pro 16",
    description: "M2 Pro Chip, 16GB RAM, 512GB SSD, Liquid Retina XDR",
    price: 2499.99,
    offer_price: 2299.99,
    discount: 8,
    quantity: 25,
    brand: "Apple",
    status: "active",
    location: "USA",
    product_shipping_fee: 0,
    product_comment: "",
    sizes: ["512GB", "1TB", "2TB"],
    colors: ["Space Grey", "Silver"],
    styles: [],
    image_url_array: [
      "/assets/macbook_image.png",
    ],
    videos_url_array: [],
    category: { id: "3", name: "Laptops" },
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    average_rating: 4.9,
    review_count: 189,
  },
  {
    id: "8",
    author_id: "",
    name: "Sony WF-1000XM5",
    description: "Noise-Cancellation, Hi-Res Audio, 8-hour battery",
    price: 299.99,
    offer_price: 279.99,
    discount: 7,
    quantity: 60,
    brand: "Sony",
    status: "active",
    location: "Japan",
    product_shipping_fee: 0,
    product_comment: "",
    sizes: [],
    colors: ["Black", "Silver"],
    styles: [],
    image_url_array: [
      "/assets/sony_airbuds_image.png",
    ],
    videos_url_array: [],
    category: { id: "1", name: "Headphones" },
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    average_rating: 4.7,
    review_count: 312,
  },
];
